import { NextResponse } from 'next/server'
import crypto from 'crypto'

const APP_URL = process.env.NEXT_PUBLIC_APP_URL || 'https://matchmindcom.com'

// ─── Types ───────────────────────────────────────────────────────────────────

interface Prediction {
  home_team: string
  away_team: string
  league: string
  leagueFlag: string
  date: string
  recommended_bet: string
  recommended_odds_range: string
  confidence: number
  risk_level: string
  home_win_pct: number
  draw_pct: number
  away_win_pct: number
  key_factors: string[]
  is_value_bet: boolean
  ev: number | null
}

// ─── Fetch today's predictions ────────────────────────────────────────────────

async function getTodaysPredictions(): Promise<Prediction[]> {
  try {
    const res = await fetch(`${APP_URL}/api/predictions`, {
      headers: { 'Cache-Control': 'no-cache' },
      next: { revalidate: 0 },
    })
    const data = await res.json()
    return data.predictions || []
  } catch (e) {
    console.error('Failed to fetch predictions:', e)
    return []
  }
}

// ─── Format helpers ───────────────────────────────────────────────────────────

function formatDate(iso: string) {
  return new Date(iso).toLocaleDateString('en-GB', {
    weekday: 'short', day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit',
    timeZone: 'Europe/London',
  })
}

function confidenceBar(score: number) {
  const filled = Math.round(score / 10)
  return '🟣'.repeat(filled) + '⬛'.repeat(10 - filled) + ` ${score}/10`
}

// ─── X (Twitter) ─────────────────────────────────────────────────────────────

function buildTweetThread(predictions: Prediction[]): string[] {
  const tweets: string[] = []
  const top3 = predictions.slice(0, 3)
  const dateStr = new Date().toLocaleDateString('en-GB', { weekday: 'long', day: 'numeric', month: 'long' })

  // Tweet 1: intro
  tweets.push(
    `🧠 MatchMind AI Picks — ${dateStr}\n\n` +
    `${top3.length} predictions generated by GPT-4 + live Bet365 odds\n\n` +
    `Thread 🧵👇`
  )

  // One tweet per prediction
  top3.forEach((p, i) => {
    const odds = p.recommended_odds_range || 'N/A'
    const emoji = p.risk_level === 'Low' ? '🟢' : p.risk_level === 'Medium' ? '🟡' : '🔴'
    tweets.push(
      `${i + 1}/${top3.length} ${p.leagueFlag} ${p.league}\n\n` +
      `${p.home_team} vs ${p.away_team}\n` +
      `⏰ ${formatDate(p.date)}\n\n` +
      `✅ Pick: ${p.recommended_bet}\n` +
      `💰 Odds: ${odds}\n` +
      `${emoji} Risk: ${p.risk_level}\n` +
      `🎯 Confidence: ${p.confidence}/10\n\n` +
      (p.key_factors?.[0] ? `📌 ${p.key_factors[0]}` : '') +
      `\n\n#FootballPredictions #${p.league.replace(/\s/g, '')} #Betting`
    )
  })

  // Final tweet: CTA
  tweets.push(
    `🔒 Pro members get all ${predictions.length} predictions + EV scores + Value Bet Finder\n\n` +
    `👉 matchmindcom.com\n\n` +
    `Bet responsibly 🙏 | Past picks: @Match_Mind_AI`
  )

  return tweets
}

async function postToTwitter(tweets: string[]): Promise<{ success: boolean; error?: string }> {
  const apiKey = process.env.TWITTER_API_KEY
  const apiSecret = process.env.TWITTER_API_SECRET
  const accessToken = process.env.TWITTER_ACCESS_TOKEN
  const accessSecret = process.env.TWITTER_ACCESS_SECRET

  if (!apiKey || !apiSecret || !accessToken || !accessSecret) {
    return { success: false, error: 'Twitter credentials not configured' }
  }

  function oauthSign(method: string, url: string, params: Record<string, string>) {
    const nonce = crypto.randomBytes(16).toString('hex')
    const timestamp = Math.floor(Date.now() / 1000).toString()

    const oauthParams: Record<string, string> = {
      oauth_consumer_key: apiKey!,
      oauth_nonce: nonce,
      oauth_signature_method: 'HMAC-SHA1',
      oauth_timestamp: timestamp,
      oauth_token: accessToken!,
      oauth_version: '1.0',
      ...params,
    }

    const sortedParams = Object.keys(oauthParams).sort()
      .map(k => `${encodeURIComponent(k)}=${encodeURIComponent(oauthParams[k])}`)
      .join('&')

    const sigBase = `${method}&${encodeURIComponent(url)}&${encodeURIComponent(sortedParams)}`
    const sigKey = `${encodeURIComponent(apiSecret!)}&${encodeURIComponent(accessSecret!)}`
    const signature = crypto.createHmac('sha1', sigKey).update(sigBase).digest('base64')

    oauthParams['oauth_signature'] = signature

    const authHeader = 'OAuth ' + Object.keys(oauthParams)
      .filter(k => k.startsWith('oauth_'))
      .map(k => `${encodeURIComponent(k)}="${encodeURIComponent(oauthParams[k])}"`)
      .join(', ')

    return authHeader
  }

  try {
    let replyToId: string | undefined

    for (const tweet of tweets) {
      const url = 'https://api.twitter.com/2/tweets'
      const body: Record<string, unknown> = { text: tweet }
      if (replyToId) body.reply = { in_reply_to_tweet_id: replyToId }

      const auth = oauthSign('POST', url, {})
      const res = await fetch(url, {
        method: 'POST',
        headers: {
          'Authorization': auth,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(body),
      })

      if (!res.ok) {
        const err = await res.text()
        return { success: false, error: `Twitter error: ${err}` }
      }

      const json = await res.json()
      replyToId = json.data?.id
    }

    return { success: true }
  } catch (e: any) {
    return { success: false, error: e.message }
  }
}

// ─── Reddit ───────────────────────────────────────────────────────────────────

function buildRedditPost(predictions: Prediction[]): { title: string; text: string } {
  const dateStr = new Date().toLocaleDateString('en-GB', { weekday: 'long', day: 'numeric', month: 'long' })
  const top = predictions.slice(0, 5)

  const rows = top.map(p =>
    `| ${p.leagueFlag} ${p.home_team} vs ${p.away_team} | ${p.recommended_bet} | ${p.recommended_odds_range || 'N/A'} | ${p.confidence}/10 |`
  ).join('\n')

  const factors = top.map((p, i) =>
    `**${i + 1}. ${p.home_team} vs ${p.away_team}**\n` +
    (p.key_factors || []).slice(0, 2).map(f => `- ${f}`).join('\n')
  ).join('\n\n')

  return {
    title: `AI Match Predictions — ${dateStr} | GPT-4 + Live Bet365 Odds`,
    text:
      `# 🧠 MatchMind AI Predictions — ${dateStr}\n\n` +
      `These picks are generated by GPT-4 using live Bet365 odds, injury data, and league form.\n\n` +
      `---\n\n` +
      `## Today's Picks\n\n` +
      `| Match | Pick | Odds | Confidence |\n` +
      `|-------|------|------|------------|\n` +
      rows + '\n\n' +
      `---\n\n` +
      `## Key Factors\n\n` +
      factors + '\n\n' +
      `---\n\n` +
      `*Full analysis + value bets at [MatchMind](${APP_URL}) | Bet responsibly 🙏*`
  }
}

async function postToReddit(title: string, text: string): Promise<{ success: boolean; error?: string }> {
  const clientId = process.env.REDDIT_CLIENT_ID
  const clientSecret = process.env.REDDIT_CLIENT_SECRET
  const username = process.env.REDDIT_USERNAME
  const password = process.env.REDDIT_PASSWORD
  const subreddit = process.env.REDDIT_SUBREDDIT || 'r/sportsbook'

  if (!clientId || !clientSecret || !username || !password) {
    return { success: false, error: 'Reddit credentials not configured' }
  }

  try {
    // Get access token
    const tokenRes = await fetch('https://www.reddit.com/api/v1/access_token', {
      method: 'POST',
      headers: {
        'Authorization': `Basic ${Buffer.from(`${clientId}:${clientSecret}`).toString('base64')}`,
        'Content-Type': 'application/x-www-form-urlencoded',
        'User-Agent': 'MatchMind/1.0',
      },
      body: `grant_type=password&username=${encodeURIComponent(username)}&password=${encodeURIComponent(password)}`,
    })

    const tokenData = await tokenRes.json()
    if (!tokenData.access_token) {
      return { success: false, error: `Reddit auth failed: ${JSON.stringify(tokenData)}` }
    }

    // Submit post
    const postRes = await fetch('https://oauth.reddit.com/api/submit', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${tokenData.access_token}`,
        'Content-Type': 'application/x-www-form-urlencoded',
        'User-Agent': 'MatchMind/1.0',
      },
      body: new URLSearchParams({
        api_type: 'json',
        kind: 'self',
        sr: subreddit.replace('r/', ''),
        title,
        text,
        nsfw: 'false',
        spoiler: 'false',
        resubmit: 'true',
      }).toString(),
    })

    const postData = await postRes.json()
    if (postData.json?.errors?.length > 0) {
      return { success: false, error: postData.json.errors[0][1] }
    }

    return { success: true }
  } catch (e: any) {
    return { success: false, error: e.message }
  }
}

// ─── Instagram ────────────────────────────────────────────────────────────────

function buildInstagramCaption(predictions: Prediction[]): string {
  const top3 = predictions.slice(0, 3)
  const dateStr = new Date().toLocaleDateString('en-GB', { weekday: 'long', day: 'numeric', month: 'long' })

  const picks = top3.map(p =>
    `${p.leagueFlag} ${p.home_team} vs ${p.away_team}\n` +
    `✅ ${p.recommended_bet} | ${p.recommended_odds_range || ''}\n` +
    `🎯 Confidence: ${p.confidence}/10`
  ).join('\n\n')

  return (
    `🧠 AI Picks — ${dateStr}\n\n` +
    picks + '\n\n' +
    `─────────────────\n` +
    `🔗 Full analysis in bio\n` +
    `Bet responsibly 🙏\n\n` +
    `#FootballPredictions #AIPredictions #SportsBetting #PremierLeague #LaLiga #Bundesliga #MatchMind #FootballTips #BettingTips #ValueBets`
  )
}

async function postToInstagram(caption: string): Promise<{ success: boolean; error?: string }> {
  const accessToken = process.env.INSTAGRAM_ACCESS_TOKEN
  const accountId = process.env.INSTAGRAM_BUSINESS_ACCOUNT_ID
  const imageUrl = process.env.INSTAGRAM_DEFAULT_IMAGE_URL

  if (!accessToken || !accountId) {
    return { success: false, error: 'Instagram credentials not configured' }
  }

  if (!imageUrl) {
    return { success: false, error: 'No default image URL configured for Instagram' }
  }

  try {
    // Step 1: Create media container
    const containerRes = await fetch(
      `https://graph.facebook.com/v19.0/${accountId}/media`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          image_url: imageUrl,
          caption,
          access_token: accessToken,
        }),
      }
    )
    const container = await containerRes.json()
    if (!container.id) return { success: false, error: `Container creation failed: ${JSON.stringify(container)}` }

    // Step 2: Publish
    const publishRes = await fetch(
      `https://graph.facebook.com/v19.0/${accountId}/media_publish`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          creation_id: container.id,
          access_token: accessToken,
        }),
      }
    )
    const pub = await publishRes.json()
    if (!pub.id) return { success: false, error: `Publish failed: ${JSON.stringify(pub)}` }

    return { success: true }
  } catch (e: any) {
    return { success: false, error: e.message }
  }
}

// ─── TikTok ───────────────────────────────────────────────────────────────────

function buildTikTokCaption(predictions: Prediction[]): string {
  const top3 = predictions.slice(0, 3)
  const dateStr = new Date().toLocaleDateString('en-GB', { weekday: 'long', day: 'numeric', month: 'long' })

  const picks = top3.map(p =>
    `${p.leagueFlag} ${p.home_team} vs ${p.away_team}: ${p.recommended_bet}`
  ).join('\n')

  return (
    `🧠 AI picks for ${dateStr}\n\n` +
    picks + '\n\n' +
    `Full analysis at MatchMind (link in bio)\n\n` +
    `#FootballPredictions #AIPicks #SportsBetting #Football #PremierLeague`
  )
}

async function createTikTokDraft(caption: string): Promise<{ success: boolean; error?: string }> {
  const clientKey = process.env.TIKTOK_CLIENT_KEY
  const accessToken = process.env.TIKTOK_ACCESS_TOKEN

  if (!clientKey || !accessToken) {
    return { success: false, error: 'TikTok credentials not configured' }
  }

  // TikTok requires a video file — we create a text-to-video style post via their API
  // For now, we initiate an upload session so the user just needs to add the video file and publish
  try {
    const res = await fetch('https://open.tiktokapis.com/v2/post/publish/inbox/video/init/', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${accessToken}`,
        'Content-Type': 'application/json; charset=UTF-8',
      },
      body: JSON.stringify({
        post_info: {
          title: caption,
          privacy_level: 'SELF_ONLY', // Draft — only visible to you
          disable_duet: false,
          disable_comment: false,
          disable_stitch: false,
          video_cover_timestamp_ms: 1000,
        },
        source_info: {
          source: 'PULL_FROM_URL',
          video_url: process.env.TIKTOK_DEFAULT_VIDEO_URL || '',
        },
      }),
    })

    const data = await res.json()
    if (data.error?.code && data.error.code !== 'ok') {
      return { success: false, error: `TikTok error: ${data.error.message}` }
    }

    return { success: true }
  } catch (e: any) {
    return { success: false, error: e.message }
  }
}

// ─── Main cron handler ────────────────────────────────────────────────────────

export async function GET(request: Request) {
  // Verify cron secret
  const authHeader = request.headers.get('authorization')
  if (authHeader !== `Bearer ${process.env.CRON_SECRET}`) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  const predictions = await getTodaysPredictions()

  if (predictions.length === 0) {
    return NextResponse.json({ success: true, message: 'No predictions today — nothing posted' })
  }

  const results: Record<string, { success: boolean; error?: string }> = {}

  // ── Twitter ──
  const tweets = buildTweetThread(predictions)
  results.twitter = await postToTwitter(tweets)

  // ── Reddit ──
  const { title, text } = buildRedditPost(predictions)
  results.reddit = await postToReddit(title, text)

  // ── Instagram ──
  const igCaption = buildInstagramCaption(predictions)
  results.instagram = await postToInstagram(igCaption)

  // ── TikTok ──
  const ttCaption = buildTikTokCaption(predictions)
  results.tiktok = await createTikTokDraft(ttCaption)

  console.log('Social post results:', JSON.stringify(results))

  return NextResponse.json({
    success: true,
    predictions_count: predictions.length,
    results,
  })
}
