import Link from 'next/link'
import { wcPromoBannerCopy, isWcPromoVisible } from '@/lib/wc-promo'

/**
 * Sticky / inline WC promo banner. Renders nothing outside the promo window.
 *
 * Variants:
 *   - "sticky"  : top-of-page promo for landing + /world-cup. High contrast,
 *                 grabs attention from TikTok-driven first-time visitors.
 *   - "inline"  : in-flow notice for /dashboard/predictions — explains why
 *                 paid tier features are visible to free users right now.
 *
 * Copy is generated by wcPromoBannerCopy() so it stays in sync with the
 * lib/wc-promo.ts date logic.
 */
export default function WcPromoBanner({
  variant = 'sticky',
  href = '/signup',
}: {
  variant?: 'sticky' | 'inline'
  href?: string
}) {
  // Server-side gate. Outside the promo window we render nothing — no DOM
  // weight, no hydration cost.
  if (!isWcPromoVisible()) return null
  const copy = wcPromoBannerCopy()
  if (!copy) return null

  if (variant === 'inline') {
    return (
      <div
        className="border border-brand/30 bg-brand/5 px-4 py-3 mb-4"
        role="status"
        aria-label="World Cup promo notice"
      >
        <p className="text-[10px] font-bold uppercase tracking-[0.18em] text-brand mb-1">
          {copy.eyebrow}
        </p>
        <p className="text-fg text-sm font-medium">{copy.headline}</p>
      </div>
    )
  }

  // Sticky variant — landing page top bar
  return (
    <Link
      href={href}
      className="block bg-brand/10 border-b border-brand/30 hover:bg-brand/15 transition-colors"
      aria-label={`${copy.eyebrow}: ${copy.headline}`}
    >
      <div className="max-w-5xl mx-auto px-5 lg:px-8 py-3 flex items-center gap-3 sm:gap-5">
        <span className="text-brand text-[10px] font-black uppercase tracking-[0.18em] shrink-0 leading-tight">
          {copy.eyebrow.split(' · ').map((part, i) => (
            <span key={i} className="block">
              {part}
            </span>
          ))}
        </span>
        <span className="text-fg text-xs sm:text-sm font-semibold leading-snug flex-1 min-w-0">
          {copy.headline}
        </span>
        <span className="text-brand text-base font-bold shrink-0" aria-hidden>
          →
        </span>
      </div>
    </Link>
  )
}
