'use client'

import { useCallback, useEffect, useState } from 'react'
import type { Currency } from './MoneyClient'

/**
 * DailyPlanTab — editorial 7-day rolling betting plan, generated by the AI
 * from the user's active Dream Bet goal + the live predictions cache.
 *
 * Top: progress strip showing current bankroll → target with % bar + days left
 * Below: 7 day-cards (Today, Tomorrow, then the next 5 days)
 *   Each day-card lists 1-3 suggested bets (highest EV inside the user's risk
 *   range), each with stake sized via the shared stake-recommender, and a
 *   one-line AI note. Empty days are framed as deliberate rest days.
 *
 * Empty state: editorial CTA "Set a Dream Bet goal first → " linking to Goals.
 */

interface SuggestedBet {
  home: string
  away: string
  league: string
  market: string
  selection: string
  odds: number
  stake: number
  ev: number
  fixtureId: number | null
  reasoning: string
  kickoff: string
}

interface DayPlan {
  date: string
  label: string
  targetBankroll: number
  suggestedBets: SuggestedBet[]
  note: string
}

interface GoalSummary {
  target: number
  daysLeft: number
  onTrack: boolean
  requiredDailyGrowthPct: number
}

interface ApiResponse {
  plan: DayPlan[] | null
  goal: GoalSummary | null
  bankroll: number
  message?: string
}

interface Props {
  currency: Currency
  /** Optional callback so the tab can switch back to "goals" if the user has none yet. */
  onSwitchToGoals?: () => void
}

function fmtMoney(n: number, currency: string): string {
  return `${currency}${Math.round(n).toLocaleString()}`
}

function fmtMoneyDecimal(n: number, currency: string): string {
  return `${currency}${n.toLocaleString(undefined, {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  })}`
}

function fmtKickoffTime(iso: string): string {
  if (!iso) return ''
  const d = new Date(iso)
  if (Number.isNaN(d.getTime())) return ''
  return d.toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit' })
}

export default function DailyPlanTab({ currency, onSwitchToGoals }: Props) {
  const [loading, setLoading] = useState(true)
  const [refreshing, setRefreshing] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [data, setData] = useState<ApiResponse | null>(null)

  const load = useCallback(async (refresh: boolean) => {
    if (refresh) setRefreshing(true)
    else setLoading(true)
    setError(null)
    try {
      const res = await fetch(
        refresh ? '/api/dream-bet/daily-plan?refresh=1' : '/api/dream-bet/daily-plan',
        { cache: 'no-store' },
      )
      const json = (await res.json()) as ApiResponse | { error: string }
      if (!res.ok) {
        throw new Error('error' in json ? json.error : 'Failed to load daily plan')
      }
      setData(json as ApiResponse)
    } catch (e: any) {
      setError(e?.message ?? 'Failed to load daily plan')
    } finally {
      setLoading(false)
      setRefreshing(false)
    }
  }, [])

  useEffect(() => {
    void load(false)
  }, [load])

  // ── Loading skeleton ───────────────────────────────────────────────
  if (loading) {
    return (
      <div className="space-y-4">
        <div className="h-28 bg-bg-surface border border-border-subtle rounded-2xl animate-pulse" />
        {Array.from({ length: 4 }).map((_, i) => (
          <div
            key={i}
            className="h-40 bg-bg-surface border border-border-subtle rounded-2xl animate-pulse"
          />
        ))}
      </div>
    )
  }

  if (error) {
    return (
      <div className="bg-loss/10 border border-loss/30 text-loss text-sm rounded-2xl p-4">
        {error}
      </div>
    )
  }

  if (!data) return null

  // ── Empty state: no active goal ────────────────────────────────────
  if (!data.plan || !data.goal) {
    return (
      <section className="bg-bg-surface border border-border-subtle rounded-2xl p-8 lg:p-12 text-center">
        <p className="eyebrow mb-3 text-brand">DAILY PLAN</p>
        <h2 className="text-fg font-black text-2xl lg:text-3xl tracking-tight mb-3">
          Set a Dream Bet goal first.
        </h2>
        <p className="text-fg-secondary text-sm lg:text-base max-w-md mx-auto mb-6">
          Once you've set a target bankroll and end date, MatchMind builds you a
          rolling 7-day plan — which bets to take each day, sized to your roll.
        </p>
        <button
          type="button"
          onClick={onSwitchToGoals}
          className="inline-flex items-center gap-2 bg-brand hover:bg-brand-hover text-bg-base font-bold py-3 px-5 rounded-lg text-sm transition-colors"
        >
          Set your goal
          <span aria-hidden>→</span>
        </button>
      </section>
    )
  }

  const goal = data.goal
  const plan = data.plan
  const bankroll = data.bankroll
  const target = goal.target
  // For the progress bar we anchor on bankroll / target as a 0-100 strip.
  // We don't have starting_bankroll in this payload, so this is a simple
  // "% of target" view rather than "% of journey covered".
  const progressPct =
    target > 0 ? Math.max(0, Math.min(100, (bankroll / target) * 100)) : 0

  return (
    <section className="space-y-5 lg:space-y-6">
      {/* PROGRESS STRIP */}
      <div className="bg-bg-surface border border-border-subtle rounded-2xl p-5 lg:p-6">
        <div className="flex items-start justify-between gap-4 mb-4">
          <div>
            <p className="eyebrow mb-2">YOUR DREAM BET</p>
            <p className="text-fg-secondary text-sm">
              <span className="font-stat font-bold text-fg text-lg lg:text-xl">
                {fmtMoneyDecimal(bankroll, currency)}
              </span>
              <span className="text-fg-muted"> · headed for </span>
              <span className="font-stat font-bold text-brand text-lg lg:text-xl">
                {fmtMoney(target, currency)}
              </span>
            </p>
            <p className="text-fg-muted text-xs mt-1.5 font-stat">
              {goal.daysLeft} {goal.daysLeft === 1 ? 'day' : 'days'} left ·
              {' '}
              {goal.requiredDailyGrowthPct >= 0 ? '+' : ''}
              {goal.requiredDailyGrowthPct.toFixed(2)}% required daily growth
            </p>
          </div>
          <button
            type="button"
            onClick={() => load(true)}
            disabled={refreshing}
            className="text-xs font-bold uppercase tracking-wider px-3 py-2 rounded-lg border border-border-subtle bg-bg-elevated hover:border-border-strong text-fg-secondary hover:text-fg transition-colors disabled:opacity-50 whitespace-nowrap"
          >
            {refreshing ? 'Refreshing…' : 'Refresh plan'}
          </button>
        </div>

        <div className="bg-bg-base rounded-full h-3 overflow-hidden border border-border-subtle">
          <div
            className={`h-full transition-all ${
              goal.onTrack
                ? 'bg-gradient-to-r from-brand to-success'
                : 'bg-gradient-to-r from-brand to-value'
            }`}
            style={{ width: `${progressPct}%` }}
            aria-hidden
          />
        </div>
        <div className="flex items-center justify-between mt-2">
          <span className="text-fg-muted text-[11px] font-stat">
            {Math.round(progressPct)}% of target
          </span>
          <span
            className={`text-[10px] font-bold uppercase tracking-wider px-2 py-0.5 rounded-full border ${
              goal.onTrack
                ? 'bg-success/15 border-success/30 text-success'
                : 'bg-value/15 border-value/30 text-value'
            }`}
          >
            {goal.onTrack ? 'On track' : 'Behind pace'}
          </span>
        </div>
      </div>

      {/* DAY CARDS */}
      <div className="space-y-4">
        {plan.map((day, idx) => (
          <DayCard
            key={day.date}
            day={day}
            currency={currency}
            highlight={idx === 0}
          />
        ))}
      </div>

      <p className="text-fg-muted text-[11px] text-center font-stat">
        Stakes are sized via fractional Kelly using your bankroll and risk profile.
        AI notes refreshed hourly; click "Refresh plan" to force a rebuild.
      </p>
    </section>
  )
}

// ── Day card ─────────────────────────────────────────────────────────

function DayCard({
  day,
  currency,
  highlight,
}: {
  day: DayPlan
  currency: Currency
  highlight: boolean
}) {
  return (
    <article
      className={`bg-bg-surface rounded-2xl p-5 lg:p-6 transition-colors ${
        highlight
          ? 'border border-brand/40'
          : 'border border-border-subtle'
      }`}
    >
      {/* Header — eyebrow + huge target bankroll */}
      <header className="flex items-end justify-between gap-3 mb-5">
        <div className="min-w-0">
          <p
            className={`eyebrow mb-1.5 ${
              highlight ? 'text-brand' : 'text-fg-muted'
            }`}
          >
            {day.label}
          </p>
          <p className="text-fg-muted text-[11px] uppercase tracking-wider font-stat">
            EOD target
          </p>
        </div>
        <p className="font-stat text-fg font-bold text-3xl lg:text-4xl leading-none">
          {fmtMoney(day.targetBankroll, currency)}
        </p>
      </header>

      {/* Suggested bets list (or empty rest-day state) */}
      {day.suggestedBets.length === 0 ? (
        <div className="bg-bg-base/50 border border-border-subtle rounded-xl px-4 py-5 text-center">
          <p className="text-fg-muted text-sm font-medium">No qualifying picks today.</p>
        </div>
      ) : (
        <div className="space-y-2.5">
          {day.suggestedBets.map((bet, i) => (
            <BetRow key={`${bet.fixtureId ?? 'na'}-${i}`} bet={bet} currency={currency} />
          ))}
        </div>
      )}

      {/* Note */}
      <p className="text-fg-secondary text-sm italic mt-4 pt-4 border-t border-border-subtle leading-relaxed">
        “{day.note}”
      </p>
    </article>
  )
}

// ── Bet row ──────────────────────────────────────────────────────────

function BetRow({ bet, currency }: { bet: SuggestedBet; currency: Currency }) {
  const [adding, setAdding] = useState(false)
  const [added, setAdded] = useState(false)
  const [errored, setErrored] = useState(false)

  async function addToBets() {
    if (adding || added) return
    setAdding(true)
    setErrored(false)
    try {
      const res = await fetch('/api/bet-slips/from-rec', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          home: bet.home,
          away: bet.away,
          market: bet.market,
          selection: bet.selection,
          odds: bet.odds,
          stake: bet.stake > 0 ? bet.stake : 1,
          league: bet.league,
          kickoff: bet.kickoff,
          reasoning: bet.reasoning,
          fixtureId: bet.fixtureId,
        }),
      })
      if (!res.ok) throw new Error('insert failed')
      setAdded(true)
    } catch {
      setErrored(true)
    } finally {
      setAdding(false)
    }
  }

  const hasStake = bet.stake > 0

  return (
    <div className="bg-bg-elevated rounded-xl px-4 py-3.5">
      {/* Top row: match + league/kickoff eyebrow */}
      <div className="flex items-baseline justify-between gap-3 mb-2 flex-wrap">
        <p className="text-fg font-bold text-sm md:text-base truncate">
          {bet.home} <span className="text-fg-muted font-medium">vs</span> {bet.away}
        </p>
        <p className="text-fg-muted text-[11px] uppercase tracking-wider font-stat truncate">
          {bet.league}
          {bet.kickoff ? ` · ${fmtKickoffTime(bet.kickoff)}` : ''}
        </p>
      </div>

      {/* Pick + odds + EV */}
      <div className="flex items-center justify-between gap-3 mb-3 flex-wrap">
        <p className="text-fg-secondary text-sm">
          <span className="text-fg-muted text-[11px] font-bold uppercase tracking-wider mr-2">
            PICK
          </span>
          <span className="text-fg font-semibold">{bet.selection}</span>
        </p>
        <div className="flex items-center gap-3 shrink-0">
          <span className="font-stat text-xl md:text-2xl font-bold text-brand leading-none">
            @{bet.odds.toFixed(2)}
          </span>
          <span className="font-stat text-[11px] font-bold text-value bg-value/10 border border-value/30 px-2 py-0.5 rounded-full whitespace-nowrap">
            {bet.ev > 0 ? '+' : ''}
            {bet.ev}% EV
          </span>
        </div>
      </div>

      {/* Stake row */}
      <div className="flex items-center justify-between gap-3 flex-wrap">
        <div className="text-fg-secondary text-xs">
          <span className="text-fg-muted text-[10px] font-bold uppercase tracking-wider mr-2">
            STAKE
          </span>
          {hasStake ? (
            <>
              <span className="text-fg font-stat font-bold text-base mr-2">
                {fmtMoneyDecimal(bet.stake, currency)}
              </span>
              <span className="text-fg-muted">recommended</span>
            </>
          ) : (
            <span className="text-fg-muted">Set bankroll for sized stake</span>
          )}
        </div>
        <button
          type="button"
          onClick={addToBets}
          disabled={adding || added || !hasStake}
          className={`text-xs font-semibold py-2 px-3 rounded-lg border transition-all duration-200 inline-flex items-center gap-1.5 ${
            added
              ? 'bg-success/10 text-success border-success/30 cursor-default'
              : errored
                ? 'bg-loss/10 text-loss border-loss/30'
                : 'bg-bg-base hover:bg-brand hover:text-bg-base text-fg border-border-subtle hover:border-brand'
          } ${!hasStake ? 'opacity-50 cursor-not-allowed' : ''}`}
        >
          <span className="text-[14px] leading-none">{added ? '✓' : '+'}</span>
          {added ? 'Added' : errored ? 'Try again' : adding ? 'Adding…' : 'Add to bets'}
        </button>
      </div>
    </div>
  )
}
